### ISSUE TITLE
Elements: Differentiate between selected and focused nodes

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4908]
It's really easy to confuse being focused on a node and able to use the arrow keys and just being selected.

We should differentiate between the two.

```css
.tag-line .tag-state.theme-selected {
  background-color: #3ac0ff;
}

.tag-line .tag-state.theme-selected:focus {
  background-color: var(--theme-selection-background);
}
```

The open question for me is how does the inspector select the next node? based on that we can add a `.focus()` in a useEffect
